name: VITALIS CI

on:
  push:
    branches:
      - develop

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo, pdo_pgsql
          coverage: none

      - name: Verifier PHP
        run: php -v

      - name: Installer les dependances Composer
        run: composer install --no-interaction --prefer-dist --no-progress